# The URL the site will be built for
base_url = "https://www.luker.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Add an automatic rss 2.0 feed
generate_feed = true
feed_filename = "rss.xml"

[extra]
# Put all your custom variables here
